name: amazoneRDP

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Downloading Ngrok.
      run: |
        Invoke-WebRequest
https://raw.githubusercontent.com/romai
n09/AWS-RDP/main/ngrok-stable-windows-
amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest
https://raw.githubusercontent.com/romai
n09/AWS-RDP/main/start.bat -OutFile
start.bat
    - name: Extracting Ngrok Files .
      run: Expand-Archive ngrok.zip
    - name: Connecting to your Ngrok
account .
      run: .\ngrok\ngrok.exe authtoken
$Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{
secrets.NGROK_AUTH_TOKEN }}
    - name: Activating RDP access.
      run: | 
        Set-ItemProperty -Path
'HKLM:\System\CurrentControlSet\Control
\Terminal Server'-name
"fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -
DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path
'HKLM:\System\CurrentControlSet\Control
\Terminal Server\WinStations\RDP-Tcp' -name
"UserAuthentication" -Value 1
        Set-LocalUser -Name "NBM" -
Password (ConvertTo-SecureString -AsPlainText
"P123@ssw0rd!" -Force)
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
